# Generated by Django 4.2.7 on 2025-08-30 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField()),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(help_text='Actual location when visit was recorded')),
                ('longitude', models.FloatField(help_text='Actual location when visit was recorded')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-arrived_at'],
                'unique_together': {('user', 'station', 'arrived_at')},
            },
        ),
    ]
